# Generated by Django 5.1.6 on 2025-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('tipo_cultivo', models.CharField(max_length=200)),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'cultivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=150)),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocria', models.CharField(db_column='CodigoCria', max_length=12)),
                ('foto', models.CharField(db_column='Foto', max_length=255)),
                ('crias', models.CharField(db_column='Crias', max_length=2)),
                ('codigoscrias', models.CharField(db_column='CodigosCrias', max_length=255)),
                ('codigopapa', models.CharField(db_column='CodigoPapa', max_length=12)),
                ('codigomama', models.CharField(db_column='CodigoMama', max_length=12)),
                ('edad', models.CharField(db_column='Edad', max_length=2)),
                ('infovacunas', models.TextField(db_column='InfoVacunas')),
                ('enfermedades', models.CharField(db_column='Enfermedades', max_length=255)),
                ('estado', models.CharField(db_column='Estado', max_length=7)),
                ('razas', models.CharField(db_column='Razas', max_length=255)),
            ],
            options={
                'db_table': 'ganado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaRazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tablarazas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('estado', models.CharField(db_column='Estado', max_length=9)),
            ],
            options={
                'db_table': 'tipoparcela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='UserName', max_length=100)),
                ('nombres', models.CharField(db_column='Nombres', max_length=120)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=70)),
                ('correo', models.CharField(db_column='Correo', max_length=255)),
                ('numerodocumento', models.CharField(db_column='NumeroDocumento', max_length=12)),
                ('rol', models.CharField(db_column='Rol', max_length=7)),
                ('clave', models.CharField(db_column='Clave', max_length=100)),
                ('estado', models.CharField(db_column='Estado', max_length=9)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
