# Generated by Django 5.1.6 on 2025-07-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0002_tipocultivo_alter_cultivo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
            ],
            options={
                'db_table': 'tablavacunas',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='tipo_cultivo',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', default=43, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.tipocultivo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fertilizante', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='AppInventario.cultivo')),
            ],
            options={
                'db_table': 'fertilizacion',
            },
        ),
    ]
